spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microsecloud-config-atguigu-dev
---
spring:
  profiles: test
  application:
    name: microsecloud-config-atguigu-test